# Generated by Django 5.0.4 on 2024-07-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('garment_type', models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant')], max_length=10)),
                ('neck_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('chest_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('waist_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('length_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
