# Generated by Django 5.0.4 on 2024-07-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_alter_order_chest_size_alter_order_length_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='garment_type',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Top-Bottom', 'Top-Bottom')], max_length=10, null=True),
        ),
    ]
