# Generated by Django 5.0.4 on 2024-07-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_alter_order_garment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='garment_type',
            field=models.CharField(choices=[('Topwear', 'Topwear'), ('Bottomwear', 'Bottomwear'), ('Top-Bottom', 'Top-Bottom')], max_length=10, null=True),
        ),
    ]
