# Generated by Django 5.0.4 on 2024-07-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_alter_order_advance_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Advance_Payment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_payment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_payment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='garment_type',
            field=models.CharField(choices=[('Topwear', 'Topwear'), ('Bottomwear', 'Bottomwear'), ('Top-Bottom', 'Top-Bottom')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
