# Generated by Django 5.0.4 on 2024-07-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_alter_order_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark_shirt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
